# Generated by Django 4.0.2 on 2022-02-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=40)),
                ('student_email', models.CharField(max_length=40)),
                ('student_password', models.CharField(max_length=40)),
            ],
        ),
    ]
